### ISSUE TITLE
Translation file

### ISSUE THREAD

**Issue by shulthz** [iamredbar/PoolTool#1]
I think this need a translation file for other language.

**Comment by iamredbar** [comment]
I completely agree! I only know English, are you multi-lingual and willing to help? I have no experience making different languages in apps.

**Comment by shulthz** [comment]
> 
> 
> I completely agree! I only know English, are you multi-lingual and willing to help? I have no experience making different languages in apps.

I'm not good at programming...., sorry about that....but when have a translation file, i can help to translat it to cn...

**Comment by iamredbar** [comment]
Thats not a problem, let me look into it a bit. I will ping you first for a CN translation, okay?

**Comment by iamredbar** [comment]
@shulthz If you wanted to, you are more than welcome to translate the README

**Comment by shulthz** [comment]
# 流动池工具
一个便于操作的比特股区块链AMM流动池界面工具。
Python编写，适用于能够运行Python的任意平台。
Telegram群：https://t.me/pooltool_community_edition

## 安装

需求：Python 3.8+
MacOS 10.14.6, Ubuntu 20.10, and 32-bit Raspberry Pi OS已测试。当前尚无Windows解决方案。

```sudo apt-get install libffi-dev libssl-dev python3-dev python3-tk```

```git clone https://github.com/iamredbar/PoolTool.git```

```cd PoolTool```

```pip3 install -r requirements.txt```

## 设置

你需要使用`uptick`设置一个默认的连接节点.语法如下：
```uptick set node <node_goes_here>```

例子:

```uptick set node 'wss://btsfullnode.bangzi.info/ws'```

**如果这一步没有完成，将不能正常运行。**

(更多关于 `uptick` : http://docs.uptick.rocks/en/latest/)

## 开始

```python3 controller.py```

## 基本操作

启动后，你可以按照你的需求在面板下拉菜单上选择流动池。

流动池工具当前支持流动池交易及充值。

## WIP | NEW SCREENSHOTS SOON

### Please report any issues you have via Github.

**Comment by iamredbar** [comment]
Thank you for doing this! Going to close this issue for right now since I will not be able to tackle something like this currently.
