### ISSUE TITLE
ERROR: bitshares 0.7.0 has requirement graphenelib<2.0.0,>=1.4.0

### ISSUE THREAD

**Issue by shulthz** [iamredbar/PoolTool#2]
ERROR: bitshares 0.7.0 has requirement graphenelib<2.0.0,>=1.4.0, but you'll have graphenelib 1.2.0 which is incompatible.

**Comment by iamredbar** [comment]
Thanks for the feedback.
After checking the requirements file, you are right where there isn't a requirement for graphenelib.
But following the instructions exactly in the README.md file, graphenelib 1.5.0 is downloaded. After installing the requirements, the program launches without error or issue.
Are you running into issues? What platform are you running it on, OS version, etc.
Here are screenshots from setting up a brand new environment to launching the app:
<img width="521" alt="Screen Shot 2020-11-07 at 10 55 19 AM" src="https://user-images.githubusercontent.com/16945982/98447184-6261a500-20e8-11eb-8450-3efe950c644d.png">
<img width="624" alt="Screen Shot 2020-11-07 at 10 56 48 AM" src="https://user-images.githubusercontent.com/16945982/98447185-62fa3b80-20e8-11eb-862b-1fabce1ae741.png">
<img width="635" alt="Screen Shot 2020-11-07 at 10 57 12 AM" src="https://user-images.githubusercontent.com/16945982/98447186-62fa3b80-20e8-11eb-9501-62d879e839a5.png">

Please provide more context or I will mark the issue as resolved.

**Comment by iamredbar** [comment]
The commit above added `graphenelib>=1.4.0` to requirements.txt
